version: '3.8'

services:
  database:
    image: mysql:8.1
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: trampo-facil
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
      
  server:
    container_name: node_server
    build: 
      dockerfile: ./docker/server.dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=trampo-facil
      - DB_USER=admin
      - DB_PASS=root
    volumes:
      - ./server:/app/server
    depends_on:
      - database
